#pragma config(Hubs,  S4, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     HTDIR,          sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S2,     TOUCH,          sensorTouch)
#pragma config(Sensor, S3,     HTDIR,          sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S4_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C4_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S4_C4_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S4_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////



/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
	servo[servo2] = 25;
	servo[servo1] = 225;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main(){
  initializeRobot();
  //waitForStart(); // Wait for the beginning of autonomous phase.

  ///////////////////////////////////////////////////////////
  ///////////////////////////////////////////////////////////
  ////                                                   ////
  ////    Add your robot specific autonomous code here.  ////
  ////                                                   ////
  ///////////////////////////////////////////////////////////
  ///////////////////////////////////////////////////////////

  nxtDisplayString(0, "Running guess beacon 101...");
  nxtDisplayString(0, "Beacon position");
  nxtDisplayString(2, "Sensor 1 value");
  nxtDisplayString(4, "Sensor 2 value");
  nxtDisplayString(3, "%d", SensorValue[S1]);
  while(true) {
  nxtDisplayString(3, "%d", SensorValue[S1]);
  }

  // Find the beacon.
  int numtick=0;
  long total_ticks = 0;
  while (numtick<100){
  	total_ticks++;
  	if (SensorValue[S1]<=5) {
  		numtick++;
  	}
  	else {
  		numtick=0;
  	}
	  motor[motorD]=50;
	  motor[motorE]=-50;
	}
  motor[motorD]=0;
  motor[motorE]=0;

  // Back up a bit.
  nxtDisplayString(0, "t = %d", total_ticks);
  if (total_ticks < 25000) {
	  motor[motorD]=-30;
	  motor[motorE]=30;
	  wait1Msec(800);
	} else {
	  motor[motorD]=-30;
	  motor[motorE]=30;
	  wait1Msec(1300);
  }
  motor[motorD]=0;
  motor[motorE]=0;

  // Drop the block.
  servo[servo2]=200;
  wait1Msec(1500);
  servo[servo2]=25;
  wait1Msec(1000);

  // Bump into the wall.
  while (SensorValue[S2] == 0) {
     motor[motorD]=100;
	   motor[motorE]=-100;
  }

  // Back up a bit.
  motor[motorD]=0;
	motor[motorE]=0;
	motor[motorD]=-50;
	motor[motorE]=50;
  wait1Msec(700);

  // Turn to the left.
  motor[motorD]=100;
  motor[motorE]=100;
  wait1Msec(1300);

  // Go forward to line up with the ramp.
  motor[motorD]=50;
  motor[motorE]=-50;
  wait1Msec(2100);

  // Turn towards the ramp.
  motor[motorD]=100;
  motor[motorE]=100;
  wait1Msec(1200);

  // Drive up onto the ramp.
  motor[motorD]=100;
  motor[motorE]=-100;
  wait1Msec(2300);

  // Stop.
  motor[motorD]=0;
  motor[motorE]=0;
}
